//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnisciPdf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnisciPdf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unisci PDF.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi.
        /// </summary>
        public static string btn_Close {
            get {
                return ResourceManager.GetString("btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea PDF unito.
        /// </summary>
        public static string btn_CreateFile {
            get {
                return ResourceManager.GetString("btn_CreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opzioni aggiuntive....
        /// </summary>
        public static string btn_Opzioni {
            get {
                return ResourceManager.GetString("btn_Opzioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        public static string btn_Reset {
            get {
                return ResourceManager.GetString("btn_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ripristina Default.
        /// </summary>
        public static string btn_SetDefault {
            get {
                return ResourceManager.GetString("btn_SetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scegli Cartella.
        /// </summary>
        public static string btnChooseFolder {
            get {
                return ResourceManager.GetString("btnChooseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome File.
        /// </summary>
        public static string dgHeader_File {
            get {
                return ResourceManager.GetString("dgHeader_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordine.
        /// </summary>
        public static string dgHeader_Number {
            get {
                return ResourceManager.GetString("dgHeader_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colori.
        /// </summary>
        public static string grpBoxColors_Header {
            get {
                return ResourceManager.GetString("grpBoxColors_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File da unire.
        /// </summary>
        public static string grpBoxFile_Header {
            get {
                return ResourceManager.GetString("grpBoxFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scala di grigi.
        /// </summary>
        public static string grpBoxGreyScale_Header {
            get {
                return ResourceManager.GetString("grpBoxGreyScale_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monocromatico.
        /// </summary>
        public static string grpBoxMonochrome_Header {
            get {
                return ResourceManager.GetString("grpBoxMonochrome_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opzioni.
        /// </summary>
        public static string grpBoxOptions_Header {
            get {
                return ResourceManager.GetString("grpBoxOptions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altro.
        /// </summary>
        public static string grpBoxOther_Header {
            get {
                return ResourceManager.GetString("grpBoxOther_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom (pt):.
        /// </summary>
        public static string lblBottom {
            get {
                return ResourceManager.GetString("lblBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprimi immagini a colori.
        /// </summary>
        public static string lblCompressColorImages {
            get {
                return ResourceManager.GetString("lblCompressColorImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprimi immagini in scala di grigi.
        /// </summary>
        public static string lblCompressGrayImages {
            get {
                return ResourceManager.GetString("lblCompressGrayImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressione.
        /// </summary>
        public static string lblCompression {
            get {
                return ResourceManager.GetString("lblCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprimi immagini monocromatiche.
        /// </summary>
        public static string lblCompressMonoImages {
            get {
                return ResourceManager.GetString("lblCompressMonoImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taglio margini (1 in = 25,4mm = 72 pt).
        /// </summary>
        public static string lblCutMargins {
            get {
                return ResourceManager.GetString("lblCutMargins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome File di destinazione (.pdf).
        /// </summary>
        public static string lblDestinationFileName {
            get {
                return ResourceManager.GetString("lblDestinationFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selezionare la cartella di destinazione.
        /// </summary>
        public static string lblDestinationFolder {
            get {
                return ResourceManager.GetString("lblDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rileva immagini duplicate.
        /// </summary>
        public static string lblDetectDuplicateImages {
            get {
                return ResourceManager.GetString("lblDetectDuplicateImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPI.
        /// </summary>
        public static string lblDPI {
            get {
                return ResourceManager.GetString("lblDPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trascinare in questa zona i file pdf.
        /// </summary>
        public static string lblfileDragDrop_Instructions {
            get {
                return ResourceManager.GetString("lblfileDragDrop_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forza conversione CYMK-&gt;RGB.
        /// </summary>
        public static string lblForceCYMKtoRGBConversion {
            get {
                return ResourceManager.GetString("lblForceCYMKtoRGBConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left (pt):.
        /// </summary>
        public static string lblLeft {
            get {
                return ResourceManager.GetString("lblLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right (pt):.
        /// </summary>
        public static string lblRight {
            get {
                return ResourceManager.GetString("lblRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soglia.
        /// </summary>
        public static string lblThreshold {
            get {
                return ResourceManager.GetString("lblThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top (pt):.
        /// </summary>
        public static string lblTop {
            get {
                return ResourceManager.GetString("lblTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendere prego....
        /// </summary>
        public static string lblWait {
            get {
                return ResourceManager.GetString("lblWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opzioni aggiuntive.
        /// </summary>
        public static string OptionPopupTitle {
            get {
                return ResourceManager.GetString("OptionPopupTitle", resourceCulture);
            }
        }
    }
}
