//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnisciPdf.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnisciPdf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unisci PDF.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Crea PDF unito.
        /// </summary>
        public static string btn_CreateFile {
            get {
                return ResourceManager.GetString("btn_CreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Annulla.
        /// </summary>
        public static string btn_Reset {
            get {
                return ResourceManager.GetString("btn_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scegli Cartella.
        /// </summary>
        public static string btnChooseFolder {
            get {
                return ResourceManager.GetString("btnChooseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome File.
        /// </summary>
        public static string dgHeader_File {
            get {
                return ResourceManager.GetString("dgHeader_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ordine.
        /// </summary>
        public static string dgHeader_Number {
            get {
                return ResourceManager.GetString("dgHeader_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File da unire.
        /// </summary>
        public static string grpBoxFile_Header {
            get {
                return ResourceManager.GetString("grpBoxFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Opzioni.
        /// </summary>
        public static string grpBoxOptions_Header {
            get {
                return ResourceManager.GetString("grpBoxOptions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bottom (pt):.
        /// </summary>
        public static string lblBottom {
            get {
                return ResourceManager.GetString("lblBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compressione.
        /// </summary>
        public static string lblCompression {
            get {
                return ResourceManager.GetString("lblCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Taglio margini (1 in = 25,4mm = 72 pt).
        /// </summary>
        public static string lblCutMargins {
            get {
                return ResourceManager.GetString("lblCutMargins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome File di destinazione (.pdf).
        /// </summary>
        public static string lblDestinationFileName {
            get {
                return ResourceManager.GetString("lblDestinationFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezionare la cartella di destinazione.
        /// </summary>
        public static string lblDestinationFolder {
            get {
                return ResourceManager.GetString("lblDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trascinare in questa zona i file pdf.
        /// </summary>
        public static string lblfileDragDrop_Instructions {
            get {
                return ResourceManager.GetString("lblfileDragDrop_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Left (pt):.
        /// </summary>
        public static string lblLeft {
            get {
                return ResourceManager.GetString("lblLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Right (pt):.
        /// </summary>
        public static string lblRight {
            get {
                return ResourceManager.GetString("lblRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Top (pt):.
        /// </summary>
        public static string lblTop {
            get {
                return ResourceManager.GetString("lblTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attendere prego....
        /// </summary>
        public static string lblWait {
            get {
                return ResourceManager.GetString("lblWait", resourceCulture);
            }
        }
    }
}
